### PR TITLE
Added 'bigquery' enpoint + other changes

### PR DESCRIPTION
**Pull request by romanchyla**
- /bigquery now exposes /solr/bigquery handler
- updated tests
- fixed bugs (ie. query parameters were not tested)
- made each test independent (to show different data)
- forced difference in GET/POST
- updated config (typo) + added VERSION
- removed POST methods from query methods
- made handlers return response.text (instead of parsing
  and re-parsing json, this was trivial, and it might have
  positive effect on execution: especially when solr returns
  lots of data)

### CODE REVIEW

**Comment by vsudilov** [comment]
Overall looks good, but the tests fail at `/resources`: I explicitly require a docstring for each view: adding a '''docstring''' to `class BigQuery` should fix that.

Also, why remove the testing of `POST` on the `SolrInterface` routes? We should test for each method that we allow IMO.

Shall I fix these minor issues, or would you like to?

**Comment by vsudilov** [comment]
Opps, I see you removed the `POST` methods. That's fine if you think there's no use case for supporting that.

**Comment by romanchyla** [comment]
thanks, i should have figured that out before pushing - it is fixed now

**Comment by vsudilov** [comment]
Seems to integrate fine into adsws, will merge and update on staging api next

**Pull request merged**
